version: "3.8"
services:
  app:
    build: .
    command: bundle exec rackup --host 0.0.0.0 -p 4567
    environment:
      - JWT_SECRET:$JWT_SECRET
      - JWT_ISSUER:$JWT_ISSUER
      - SECRET:$SECRET
    ports:
      - "4567:4567"
    volumes:
      - .:/src

